# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marshall_subset <- function(Y, s, e, betas, alphas) {
    .Call('_subset_marshall_subset', PACKAGE = 'subset', Y, s, e, betas, alphas)
}

marshall_wbs_subset <- function(data, M, zeta, betas, alphas, seed) {
    .Call('_subset_marshall_wbs_subset', PACKAGE = 'subset', data, M, zeta, betas, alphas, seed)
}

marshall_wbs <- function(data, M, zeta, seed) {
    .Call('_subset_marshall_wbs', PACKAGE = 'subset', data, M, zeta, seed)
}

